name: Update Live Test Map

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo with PAT
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git clone https://x-access-token:${GH_PAT}@github.com/${{ github.repository }} repo
          cd repo

          echo "Setting up Python..."
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install requests

          echo "Running update script..."
          python3 update_map.py

          echo "Committing changes..."
          git config user.name "aj-map-bot"
          git config user.email "aj@users.noreply.github.com"
          git add test_map.geojson
          git commit -m "Update test map" || echo "No changes"
          git push
