name: Update Test Map

on:
  schedule:
    - cron: "*/30 * * * *"  # Runs every 30 minutes (or adjust to your preferred schedule)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Ensures GITHUB_TOKEN has write permissions to push changes

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: pip install requests

      # Step 4: Run the update script to fetch data and update GeoJSON
      - name: Run update script
        run: python update_map.py

      # Step 5: Commit and push the updated GeoJSON file using GITHUB_TOKEN
      - name: Commit and push updated GeoJSON
        run: |
          git config --global user.name "aj-map-bot"
          git config --global user.email "aj@users.noreply.github.com"
          
          # Force the remote URL to always use the GITHUB_TOKEN for authentication
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

          # Pull the latest changes from the repository using GITHUB_TOKEN
          git pull origin main

          # Add, commit, and push changes using the GITHUB_TOKEN for push
          git add test_map.geojson
          git commit -m "Update test map" || echo "No changes"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} main
