name: Update Live Test Map

on:
  schedule:
    - cron: "*/30 * * * *"  # every 30 minutes
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python update_map.py

      - name: Commit and push updated GeoJSON
        run: |
          git config --global user.name "aj-map-bot"
          git config --global user.email "aj@users.noreply.github.com"
          
          # Use the built-in GITHUB_TOKEN provided by GitHub Actions
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          
          # Pull the latest changes from the repository using the built-in token
          git pull https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} main
          
          # Add, commit, and push changes using the built-in token
          git add test_map.geojson
          git commit -m "Update test map" || echo "No changes"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} main
